version: '2.4'

services:
  # Postgres
  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: task-management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container_task_management
    host: host.docker.internal
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: dangnhatminh127@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - '5050:80'

  # # Redis
  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   expose:
  #     - 6379
